export { source as torrents } from "./the-pirate-bay"
export { source as weather } from "./weather"
export { source as oil } from "./crude-oil"
export { source as irs } from "./irs"
export { source as fuel } from "./fuel"
export { source as news } from "./news"
export { source as aqi } from "./aqi"
export { source as fx } from "./fx"
